### ISSUE TITLE
Déplacer les chants dans la playlist fonctionne mal sous Firefox

### ISSUE THREAD

**Issue by DamienVicet** [clementh44/scrolleur-chanteur#4]
Sous Firefox, pour changer l'ordre des chants de la playlist, il faut vraiment bien cliquer sur l'image de la flèche pour que ça fonctionne. Sous Chrome, il suffit de cliquer sur le bouton.

**Comment by clementh44** [comment]
C'est corrigé avec la v4.13.0
passage d'un <button> à un <i>. Sûrement un problème de comportement par défaut d'un élément <button>
